######################################################################
# Automatically generated by qmake (2.01a) ?t 14. VI 13:19:02 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Field.h hello.h quitwin.h SlidComp.h
SOURCES += Field.cpp hello.cpp main.cpp quitwin.cpp SlidComp.cpp
