######################################################################
# Automatically generated by qmake (2.01a) út 12. VI 18:04:37 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += hello.h quitwin.h SlidComp.h
SOURCES += hello.cpp main.cpp quitwin.cpp SlidComp.cpp
